export const mock = [
  {
    category: "Entertainment: Television",
    type: "multiple",
    difficulty: "medium",
    question: "In the TV series &quot;Person of Interest&quot;, who plays the character &quot;Harold Finch&quot;?",
    correct_answer: "Michael Emerson",
    incorrect_answers: ["Jim Caviezel", "Taraji P. Henson", "Kevin Chapman"],
  },
  {
    category: "History",
    type: "multiple",
    difficulty: "medium",
    question: "In relation to the British Occupation in Ireland, what does the IRA stand for.",
    correct_answer: "Irish Republican Army",
    incorrect_answers: [
      "Irish Rebel Alliance",
      "Irish Reformation Army",
      "Irish-Royal Alliance",
    ],
  },
  {
    category: "Sports",
    type: "multiple",
    difficulty: "medium",
    question: "Which nation hosted the FIFA World Cup in 2006?",
    correct_answer: "Germany",
    incorrect_answers: ["United Kingdom", "Brazil", "South Africa"],
  },
  {
    category: "History",
    type: "multiple",
    difficulty: "medium",
    question: "Adolf Hitler was born on which date?",
    correct_answer: "April 20, 1889",
    incorrect_answers: ["June 12, 1889", "February 6, 1889", "April 16, 1889"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "hard",
    question: "The creeper in Minecraft was the result of a bug while implementing which creature?",
    correct_answer: "Pig",
    incorrect_answers: ["Zombie", "Chicken", "Cow"],
  },
  {
    category: "Science & Nature",
    type: "multiple",
    difficulty: "hard",
    question: "What is the unit of electrical inductance?",
    correct_answer: "Henry",
    incorrect_answers: ["Weber", "Coulomb", "Mho"],
  },
  {
    category: "Art",
    type: "multiple",
    difficulty: "hard",
    question: "Which of these is not an additional variation of the color purple?",
    correct_answer: "Kobicha",
    incorrect_answers: ["Byzantium", "Pomp and Power", "Palatinate"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "medium",
    question: "Which ones of these Mario Kart games was made for the Gameboy Advance?",
    correct_answer: "Mario Kart: Super Circuit",
    incorrect_answers: [
      "Mario Kart: Double Dash",
      "Mario Kart 64",
      "Super Mario Kart",
    ],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "hard",
    question: "What is the name of the main island in PLAYERUNKNOWN&#039;S BATTLEGROUNDS?",
    correct_answer: "Erangel",
    incorrect_answers: ["Marmara", "Severny", "Lastovo"],
  },
  {
    category: "Entertainment: Board Games",
    type: "multiple",
    difficulty: "hard",
    question: "What was the development code name for the &quot;Urza&#039;s Destiny&quot; expansion for &quot;Magic: The Gathering&quot;, released in 1999?",
    correct_answer: "Chimichanga",
    incorrect_answers: ["Burrito", "Taquito", "Enchilada"],
  },
];
